### ISSUE TITLE
program slicing

### ISSUE THREAD

**Issue by lyqssb** [LPhD/Jess#2]
hello! I am trying to use Jess to get program slicing. But after I read docs,I still don't know how to make it work.
There are my steps:
 first, I want to get all the ''callees and their ids'' of  my  code files.
 second , get these nodes's slicing and  codes. 
But when I import the codes as  tarball into the server and `python3 SUI.py`, I don't know the next thing I should do.Do I miss something? Is there a direct command to make it work? such as joern-slice?
Thank you!

**Comment by LPhD** [comment]
Hey,
do you use the stable version and was the import of your project sucessfull?
When you start the SUI.py, there should be a terminal dialogue that guides you through the necessary steps (e.g. selecting an entry point for the slicing process).

Furthermore (if I understand you correctly), you would like to get the slice for several lines of code (all nodes that are callees), right?
Currently, the SUI script only supports entry points that are either given via a feature name (the part after an #ifdef) or via location in your project (filename + line). But you can utilize the project's graph and run a query beforehead to find the desired statements with the queries.py script (you need to add your project's name manually at the beginning and the query at the end of the script just before the "Execute query" comment)). You need something like "g.V().has('type", 'Callee').values('location')", which will return the location of all nodes in your project that are callees.

**Comment by lyqssb** [comment]
Wow, I just saw the mail. Thank you for your response.You understood exactly what I said!
I can get the dialogue that you said. I want to get all Callee nodes as my entry nodes, and I've already used joern to obtain these nodes. the command  I used:
echo ' queryNodeIndex("type:Callee").id' | joern-lookup -g | joern-location > location.txt
I don't know that the usage of Jess via location means, do the code file should be in the same directory with SUI.py? May I just 
 only use the node id to get my slicing?  would you mind giving me an example? such as after I chose 2 , what exactly the terminal ask me to input? Thank you very much! @LPhD

**Comment by LPhD** [comment]
Great that you already have the node ids and the location. However, I'm wondering if these are the ids of the nodes from the graph that you imported with" jess-import"? Because in the Jess project, there are (or should be) no more commands that contain "joern".

If you would like to work with multiple node ids as entry points, just deactivate this console dialoge in the SUI.py and fill in the node ids manually.
Open SUI.py with an editor of your choice. Set "console = False" in line 30.
Set your projectname in "projectName = 'YourNameHere'" in line 44.
Add your node ids in line 70 as comma separated list, e.g. "entryPointIds = {123, 456, 789}"

Save and run the script via python3 SUI.py, the jess server must be running in parallel.

Your project's code doesn't have to be in the same folder, as the script is only interacting with the imported code property graph.



The terminal dialoge is just a help for beginners (if you don't know how to get the desired node ids). It currently only works for one id/node as entry point.
The usage is as follows (when console is set to true in SUI.py):
First you need to start the jess server in one terminal.
In the other terminal, run the SUI script. 
First, select the name of the desired project, e.g. "ExampleProject".
Then (as you already did) select "2".
Next, you need to specify the relative path of your entry point within your project structure. E.g. my entry point is in ExampleProject/src/main.c so I need to type in "/src/main.c"
Next, it asks for the line number of your entry point (the line in the file where the code statement is), e.g. "42".
It now gives you a list of all nodes, their code, type, and their ids which belong to this specific location. Just select the id of one node, e.g. "12345" and then the process automatically searches for all semantically related lines to that node. This may take a while, depending on the size of your code base and the resulting slice.

**Comment by lyqssb** [comment]
I'm not quite sure What you mean. How could I use with 'Jess-import'? I tried to tar my code file directory and rename it ProjectName. But this compressed package which I 'Jess-import' is not the same one with I used in Joern. As you know ,the .joernIndex.h is the joern database location. Should I let it in the Jess? such as Jess-import .joernIndex.h? Obviously, for these two tools, I used same code file directory.But in Jess, I got a ProjectName through compressed package. And I got .joernIndex.h through Java -jar in Joern. Could they be the same thing? Or could their node ids  be the same number?
I don't know if I made myself clear. Thank you very much for your reply! @LPhD

**Comment by LPhD** [comment]
Jess and Joern are two separate projects and not compatible with each other, as Jess is a derivative of Joern. If you'd like to use the SUI slicing script, you need to work with the Jess graph and db. Please read https://jess.readthedocs.io/en/stable/installation.html and https://jess.readthedocs.io/en/stable/import.html on how to install and run Jess and then import your project. Sadly, it's not possible to reuse the Joern db (differing structure) or their indices (they were newly created every time you import a project, either in Jess or Joern).
ProjectName was just a placeholder for however you like to name your project.
