### ISSUE TITLE
use program slice 

### ISSUE THREAD

**Issue by sh1527118023** [LPhD/Jess#3]
![image](https://user-images.githubusercontent.com/85605540/127258432-94356e70-5535-4996-b0b2-66a7324f2654.png)
How should I use Jess in specific projects? For example, where should I write the project name and entry point, are there specific examples?

**Comment by LPhD** [comment]
Thank you for trying out Jess :)
The answer to your question depends on whether you use the interactive console (recommended) or would like to edit it manually. Have you tried running the script as it is described in the manual? Then it shoud guide you with questions ("What is the name ouf your project").
Otherwise, in the SUI.py script there are example values set for the variable "projectName", but then you'd have to deactivate the interactive console for this value to take effect.
Generally, the projectName is just a String (same String you used for the "jess-import" command) and the location is either a String (name of a configuration option) or a combination of path and line number.
